//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chimera.Resources.Admin.Website.Controllers.AdminUser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chimera.Resources.Admin.Website.Controllers.AdminUser.UserMessages", typeof(UserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password field is required when adding a new admin user..
        /// </summary>
        public static string Add_New_Password_Required_Fail {
            get {
                return ResourceManager.GetString("Add_New_Password_Required_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is required to be at least 8 characters, have lowercase and uppercase letters, and at least 1 number..
        /// </summary>
        public static string Add_New_Password_Strength_Failed {
            get {
                return ResourceManager.GetString("Add_New_Password_Strength_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password field must match the password repeat field when adding a new user..
        /// </summary>
        public static string Add_New_Passwords_Dont_Match_Fail {
            get {
                return ResourceManager.GetString("Add_New_Passwords_Dont_Match_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully added the new admin user [USERNAME]..
        /// </summary>
        public static string Add_New_Saved_Success {
            get {
                return ResourceManager.GetString("Add_New_Saved_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username field is required when adding a new admin user..
        /// </summary>
        public static string Add_New_Username_Required_Fail {
            get {
                return ResourceManager.GetString("Add_New_Username_Required_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully updated the admin user [USERNAME]..
        /// </summary>
        public static string Edit_Saved_Success {
            get {
                return ResourceManager.GetString("Edit_Saved_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to finalize the save of the new/updated admin user.  Please try again or contact a system administrator..
        /// </summary>
        public static string Unable_To_Complete_Save_Default_Fail {
            get {
                return ResourceManager.GetString("Unable_To_Complete_Save_Default_Fail", resourceCulture);
            }
        }
    }
}
